Repository StudyConnect-ZHAW/Frontend, pull requests merged in 2025-05, with the labels that each got.

#68 feat/#67_upgrade-node-version
  docker/Dockerfile
  package-lock.json
  package.json
Labels: dependencies

#69 feat/NOISSUE increase token scope
  src/app/auth/login/route.ts
Labels: feat

#53 feat/#51_translation-of-UI-Text
  package-lock.json
  package.json
  public/locales/de-CH/calendar.json
  public/locales/de-CH/chat.json
  public/locales/de-CH/common.json
  public/locales/de-CH/forum.json
  public/locales/de-CH/groups.json
  public/locales/de-CH/preferences.json
  public/locales/en-GB/calendar.json
  public/locales/en-GB/chat.json
  public/locales/en-GB/common.json
  public/locales/en-GB/forum.json
  public/locales/en-GB/groups.json
  public/locales/en-GB/preferences.json
  src/app/chat/page.tsx
  src/app/forum/page.tsx
  src/app/groups/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/preferences/AccountSettings.tsx
  src/app/preferences/AppearanceSettings.tsx
  src/app/preferences/GeneralSettings.tsx
  src/app/preferences/NotificationSettings.tsx
  src/app/preferences/PrivacySettings.tsx
  src/app/preferences/ProfileSettings.tsx
  src/app/preferences/page.tsx
  src/components/AppShell.tsx
  src/components/Footer.tsx
  src/i18n/config.ts
  src/i18n/index.ts
  tsconfig.json
Labels: feat

#71 Feat/#65 implement a UI for timetable calender
  next.config.ts
  package-lock.json
  package.json
  public/locales/de-CH/calendar.json
  public/locales/en-GB/calendar.json
  src/app/api/calendar/route.ts
  src/app/calendar/page.tsx
  src/app/page.tsx
  src/components/Calendar.tsx
  src/lib/api/openholidays.ts
  src/lib/calendar.ts
  src/types/calendar.ts
  src/types/openholidays.ts
Labels: feat

#78 Feat/#72 switch email in preferences and route handlers for backend API
  .github/actions/run-frontend-tests/action.yaml
  public/locales/de-CH/common.json
  public/locales/de-CH/preferences.json
  public/locales/en-GB/common.json
  public/locales/en-GB/preferences.json
  src/app/api/categories/[cid]/route.ts
  src/app/api/categories/route.ts
  src/app/api/comments/[cmid]/likes/route.ts
  src/app/api/comments/[cmid]/route.ts
  src/app/api/groups/[groupId]/members/[userId]/route.ts
  src/app/api/groups/[groupId]/members/route.ts
  src/app/api/groups/[groupId]/route.ts
  src/app/api/groups/route.ts
  src/app/api/me/route.ts
  src/app/api/posts/[pid]/comments/route.ts
  src/app/api/users/[userId]/groups/route.ts
  src/app/api/users/[userId]/owned/route.ts
  src/app/api/users/[userId]/route.ts
  src/app/api/users/route.ts
  src/app/auth/redirect/route.ts
  src/app/login/page.tsx
  src/app/preferences/AccountSettings.tsx
  src/lib/api/parseResponse.ts
  src/lib/api/proxyRequest.ts
  src/lib/handlers/userHandler.ts
  src/types/forum.ts
  src/types/user.ts
Labels: feat

#82 FIX/NOISSUE_HOTFIX-First-Time-Login-And-Groups-Page
  src/app/auth/logout/route.ts
  src/app/auth/redirect/route.ts
  src/components/GroupCard.tsx
  src/hooks/useGroups.ts
  src/types/group.ts
Labels: fix
