Repository StudyConnect-ZHAW/Frontend, pull requests merged in 2025-03, with the labels that each got.

#5 PR: Initial project structure
  .gitignore
  README.md
  eslint.config.mjs
  next.config.ts
  package-lock.json
  package.json
  postcss.config.mjs
  public/file.svg
  public/globe.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  tsconfig.json
Labels: enhancement

#17 Ci/#16 setup cicd
  .github/workflows/build.yaml
  .github/workflows/ci-cd-staging.yaml
  README.md
  docker/.dockerignore
  docker/Dockerfile
  docker/compose.yaml
  docker/entrypoint.sh
  next.config.ts
  package-lock.json
  package.json
  sonar-project.properties
  src/__tests__/dummy.test.ts
  vitest.config.ts
Labels: ci

#28 Ci/NOISSUE fix cicd
  .github/workflows/ci-cd-staging.yaml
  docker/Dockerfile
  docker/compose.yaml
  docker/entrypoint.sh
Labels: fix, ci

#32 Ci/noissue fix build perm
  .github/workflows/ci-cd-staging.yaml
Labels: ci, patch

#35 feat/#25_implemented-home-screen-with-components
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/fonts/poppins.css
  public/logo-old.png
  public/site.webmanifest
  src/app/calendar/page.tsx
  src/app/chat/page.tsx
  src/app/components/button/button.css
  src/app/components/calender/calender.css
  src/app/components/callToAction/cta.css
  src/app/components/chatChannel/chatChannel.css
  src/app/components/footer/footer.css
  src/app/components/forumPost/forumPost.css
  src/app/components/header/header.css
  src/app/components/index.css
  src/app/components/profile/profile.css
  src/app/components/shortcut/shortcut.css
  src/app/components/sidebar/sidebar.module.css
  src/app/components/sidebar/sidebar.tsx
  src/app/components/text/text.css
  src/app/favicon.ico
  src/app/forum/page.tsx
  src/app/groups/page.tsx
  src/app/layout.tsx
  src/app/login/login.module.css
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/profile/page.tsx
  src/app/settings/page.tsx
  src/app/styles.css
  src/components/AuthPanel.tsx
  src/components/Button.tsx
  src/components/Calendar.tsx
  src/components/DirectChat.tsx
  src/components/Footer.tsx
  src/components/ForumPost.tsx
  src/components/GroupChat.tsx
  src/components/Logo.tsx
  src/components/PageHeader.tsx
  src/components/ProfileCard.tsx
  src/components/Shortcut.tsx
  src/components/Sidebar.tsx
  src/components/WIPSection.tsx
Labels: feat

#34 ci/#33 SonarQube PR decoration
  .github/actions/run-frontend-tests/action.yaml
  .github/workflows/build.yaml
  .github/workflows/ci-cd-staging.yaml
Labels: ci, patch
