Repository StudyConnect-ZHAW/Frontend, pull requests merged in 2025-04, with the labels that each got.

#40 Feat/#20 profile management UI
  src/app/profile/page.tsx
Labels: feat

#42 ci/[NOISSUE] fix frontend build
  .github/workflows/ci-cd-staging.yaml
Labels: fix, ci

#44 chore/NOISSUE template adjustment
  .github/pull_request_template.md
Labels: chore

#41 Feat/#37 darkmode
  src/app/fonts/poppins.css
  src/app/globals.css
  src/app/styles.css
  src/components/DarkToggle.tsx
  src/components/Sidebar.tsx
  tailwind.config.js
Labels: feat

#51 Fix/#48 fix hydration error
  README.md
  package-lock.json
  src/app/page.tsx
Labels: fix

#54 Feat/#21 microsoft sso integration trigger redirect
  .example.env
  .github/workflows/build.yaml
  docker/compose.yaml
  next.config.ts
  package-lock.json
  package.json
  src/app/api/me/route.ts
  src/app/auth/login/route.ts
  src/app/auth/logout/route.ts
  src/app/auth/redirect/route.ts
  src/app/layout.tsx
  src/app/login/login.module.css
  src/app/page.tsx
  src/components/AuthPanel.tsx
  src/lib/msal.ts
  src/middleware.ts
  tailwind.config.js
  tsconfig.json
Labels: bug, feat

#61 bug/#60 cannot login in live site
  .example.env
  src/app/auth/redirect/route.ts
  src/app/globals.css
  src/app/page.tsx
  src/app/styles.css
Labels: bug, fix
